# These are supported funding model platforms
github: [pkalosh]
patreon: pkalosh # Replace with a single Patreon username
ko_fi: patrickkioko
buy_me_a_coffee: BP7rDOx20C
custom: ['https://paypal.me/pkalosh']
