# These are supported funding model platforms
github: [pkalosh]
patreon: pkalosh # Replace with a single Patreon username
ko_fi: pkalosh
tidelift: pypi
buy_me_a_coffee: pkalosh
custom: ['https://paypal.me/pkalosh']
